/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AdminFuncoesRouteImport } from './routes/admin-funcoes'
import { Route as AdminLoginRouteImport } from './routes/admin-login'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as EmpresaRouteImport } from './routes/empresa'
import { Route as MudancasRouteImport } from './routes/mudancas'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as ReservasRouteImport } from './routes/reservas'
import { Route as ViaturaIdRouteImport } from './routes/viatura.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFuncoesRoute = AdminFuncoesRouteImport.update({
  id: '/admin-funcoes',
  path: '/admin-funcoes',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin-login',
  path: '/admin-login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpresaRoute = EmpresaRouteImport.update({
  id: '/empresa',
  path: '/empresa',
  getParentRoute: () => rootRouteImport,
} as any)
const MudancasRoute = MudancasRouteImport.update({
  id: '/mudancas',
  path: '/mudancas',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservasRoute = ReservasRouteImport.update({
  id: '/reservas',
  path: '/reservas',
  getParentRoute: () => rootRouteImport,
} as any)
const ViaturaIdRoute = ViaturaIdRouteImport.update({
  id: '/viatura/$id',
  path: '/viatura/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin-funcoes': typeof AdminFuncoesRoute
  '/admin-login': typeof AdminLoginRoute
  '/auth': typeof AuthRoute
  '/empresa': typeof EmpresaRoute
  '/mudancas': typeof MudancasRoute
  '/perfil': typeof PerfilRoute
  '/reservas': typeof ReservasRoute
  '/viatura/$id': typeof ViaturaIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin-funcoes': typeof AdminFuncoesRoute
  '/admin-login': typeof AdminLoginRoute
  '/auth': typeof AuthRoute
  '/empresa': typeof EmpresaRoute
  '/mudancas': typeof MudancasRoute
  '/perfil': typeof PerfilRoute
  '/reservas': typeof ReservasRoute
  '/viatura/$id': typeof ViaturaIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin-funcoes': typeof AdminFuncoesRoute
  '/admin-login': typeof AdminLoginRoute
  '/auth': typeof AuthRoute
  '/empresa': typeof EmpresaRoute
  '/mudancas': typeof MudancasRoute
  '/perfil': typeof PerfilRoute
  '/reservas': typeof ReservasRoute
  '/viatura/$id': typeof ViaturaIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin-funcoes'
    | '/admin-login'
    | '/auth'
    | '/empresa'
    | '/mudancas'
    | '/perfil'
    | '/reservas'
    | '/viatura/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/admin-funcoes'
    | '/admin-login'
    | '/auth'
    | '/empresa'
    | '/mudancas'
    | '/perfil'
    | '/reservas'
    | '/viatura/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin-funcoes'
    | '/admin-login'
    | '/auth'
    | '/empresa'
    | '/mudancas'
    | '/perfil'
    | '/reservas'
    | '/viatura/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AdminFuncoesRoute: typeof AdminFuncoesRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AuthRoute: typeof AuthRoute
  EmpresaRoute: typeof EmpresaRoute
  MudancasRoute: typeof MudancasRoute
  PerfilRoute: typeof PerfilRoute
  ReservasRoute: typeof ReservasRoute
  ViaturaIdRoute: typeof ViaturaIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-funcoes': {
      id: '/admin-funcoes'
      path: '/admin-funcoes'
      fullPath: '/admin-funcoes'
      preLoaderRoute: typeof AdminFuncoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-login': {
      id: '/admin-login'
      path: '/admin-login'
      fullPath: '/admin-login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empresa': {
      id: '/empresa'
      path: '/empresa'
      fullPath: '/empresa'
      preLoaderRoute: typeof EmpresaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mudancas': {
      id: '/mudancas'
      path: '/mudancas'
      fullPath: '/mudancas'
      preLoaderRoute: typeof MudancasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reservas': {
      id: '/reservas'
      path: '/reservas'
      fullPath: '/reservas'
      preLoaderRoute: typeof ReservasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/viatura/$id': {
      id: '/viatura/$id'
      path: '/viatura/$id'
      fullPath: '/viatura/$id'
      preLoaderRoute: typeof ViaturaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AdminFuncoesRoute: AdminFuncoesRoute,
  AdminLoginRoute: AdminLoginRoute,
  AuthRoute: AuthRoute,
  EmpresaRoute: EmpresaRoute,
  MudancasRoute: MudancasRoute,
  PerfilRoute: PerfilRoute,
  ReservasRoute: ReservasRoute,
  ViaturaIdRoute: ViaturaIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
